baseURL = 'https://TheKyleRand.github.io/blog-site/'
languageCode = 'en-us'
title = "Kyle's Tech Blog"
theme = 'm10c'

[params]
    author = 'Kyle Rand'
    description = 'A blog about technology and programming'
    favicon = '/blog-site/favicon.ico'
    
    [[params.social]]
        icon = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/kylerand"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true


[module]
    [[module.mounts]]
        source = 'static'
        target = 'static'